# Generated by Django 3.2.4 on 2021-07-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('rutColaborador', models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut del Colaborador')),
                ('imgColaborador', models.ImageField(upload_to='colaborador/', verbose_name='Imagen/Logo del Colaborador')),
                ('nombreColaborador', models.CharField(max_length=150, verbose_name='Nombre del Colaborador')),
                ('telefColaborador', models.IntegerField(verbose_name='Telefono del Colaborador')),
                ('direccionColaborador', models.CharField(max_length=250, verbose_name='Dirección del Colaborador')),
                ('emailColaborador', models.CharField(max_length=100, verbose_name='Email del Colaborador')),
                ('paisColaborador', models.CharField(max_length=100, verbose_name='Pais del Colaborador')),
                ('contraseñaColaborador', models.CharField(max_length=8, verbose_name='Contraseña Colaborador')),
            ],
        ),
    ]
